global DEFINITIONS

DEFINITIONS.SENTSTART = 'SENTSTART';
DEFINITIONS.SENTEND = 'SENTEND';

DEFINITIONS.STAR = 'STAR_';
DEFINITIONS.COMMA = 'COMMA_';
DEFINITIONS.PERIOD = 'PERIOD_';
DEFINITIONS.QUESTION = 'QUESTION_';
DEFINITIONS.EXCLAM = 'EXCLAM_';
DEFINITIONS.DASH = 'DASH_';
DEFINITIONS.PLUS = 'PLUS_';
DEFINITIONS.EQUALS = 'EQUALS_';
DEFINITIONS.COLON = 'COLON_';
DEFINITIONS.SEMICOLON = 'SEMICOLON_';
DEFINITIONS.BACKQUOTE = 'BACKQUOTE_';
DEFINITIONS.SINGQUOTE = 'SINGQUOTE_';
DEFINITIONS.DOUBQUOTE = 'DOUBQUOTE_';
DEFINITIONS.OPENPAREN = 'OPENPAREN_';
DEFINITIONS.CLOSEPAREN = 'CLOSEPAREN_';
DEFINITIONS.OPENBRACK = 'OPENBRACK_';
DEFINITIONS.CLOSEBRACK = 'CLOSEBRACK_';
DEFINITIONS.SLASH = 'SLASH_';
DEFINITIONS.DOLLAR = 'DOLLAR_';
DEFINITIONS.PERCENT = 'PERCENT_';
DEFINITIONS.AMPERSAND = 'AMPERSAND_';
DEFINITIONS.LESS = 'LESS_';
DEFINITIONS.GREATER = 'GREATER_';


DEFINITIONS.ONE = 'ONE_';
DEFINITIONS.TWO = 'TWO_';
DEFINITIONS.THREE = 'THREE_';
DEFINITIONS.FOUR = 'FOUR_';
DEFINITIONS.FIVE = 'FIVE_';
DEFINITIONS.SIX = 'SIX_';
DEFINITIONS.SEVEN = 'SEVEN_';
DEFINITIONS.EIGHT = 'EIGHT_';
DEFINITIONS.NINE = 'NINE_';
DEFINITIONS.ZERO = 'ZERO_';